CodeDrillz/config/routes.rb
Rails.application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # devise_for :users, ActiveAdmin::Devise.config
  # , ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :groups do
    resources :drills
  end

  resources :categories
  get "/users/profile" => "users#show", as: :profile
  resources :users
  # devise_for :users, controllers: {
          # sessions: 'users/sessions'
        # }

  # get "users/create" => "users#create", as: :user_sign_up

  post "/homes/:drill_id/add" => "homes#create", as: :add_drill

  resources :homes
  resources :badges
  root "homes#welcome"
  get "/welcome" => "homes#welcome", as: :welcome


end
# every single file in views/users is junk & should eventually be deleted.
# everything you'd think to be in that folder is actually in views/devise

CodeDrillz/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

CodeDrillz/app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :earned_badges, through: :groups
end

CodeDrillz/app/models/categorizing.rb
class Categorizing < ActiveRecord::Base
  belongs_to :category
  belongs_to :group
end

CodeDrillz/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorizings, dependent: :nullify
  has_many :groups, through: :categorizings

  validates :title, presence: true

  
end

CodeDrillz/app/models/drill.rb
class Drill < ActiveRecord::Base
  belongs_to :group
  has_many   :solutions, dependent: :destroy
  accepts_nested_attributes_for :solutions, reject_if: :all_blank, allow_destroy: true
  has_many :user_drills, dependent: :destroy
  has_many :user, through: :user_drills

  validates :description, presence: true

  def to_s
    self.description
  end

end

CodeDrillz/app/models/earned_badge.rb
class EarnedBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  belongs_to :group
end

CodeDrillz/app/models/group.rb
class Group < ActiveRecord::Base

  has_many :categories, through: :categorizings
  # belongs_to :user

  has_many :drills, dependent: :destroy
  has_many :categorizings, dependent: :nullify
  has_many :categories, through: :categorizings
  has_many :group_badges, dependent: :nullify
  has_many :badges, through: :group_badges
  has_many :earned_badges, dependent: :nullify

  validates :name, presence: true
  validates :level, presence: true
end

CodeDrillz/app/models/group_badge.rb
class GroupBadge < ActiveRecord::Base
  belongs_to :group
  belongs_to :badge
end

CodeDrillz/app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
end

CodeDrillz/app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :drill

  validates :correct_answer, presence: true
  validates :solution_type, presence: true
end

CodeDrillz/app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_many :points, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :earned_badges, through: :groups
  has_many :user_drills, dependent: :destroy
  has_many :drills, through: :user_drills

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def self.send_reset_password_instructions(attributes={})
     recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
     if !recoverable.approved?
       recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
     elsif recoverable.persisted?
       recoverable.send_reset_password_instructions
     end
     recoverable
   end
end

CodeDrillz/app/models/user_drill.rb
class UserDrill < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill
end

CodeDrillz/app/controllers/badges_controller.rb
class BadgesController < ApplicationController

    before_action :badge, only: [:show, :edit, :update, :destroy]

    # ----------------------------------------------------------------------------
      def badge
        @badge ||= Badge.find params[:id]
      end
      def badge_params
        params.require(:badge).permit([:url])
      end
    # ----------------------------------------------------------------------------

    def index
      @badge = Badge.all
    end

    def new
      @badge = Badge.new
    end

    def create
      # render text: badge_params

      @badge = Badge.new(badge_params)
      # @badge.user = current_user
      if @badge.save
        redirect_to(badges_path, notice: "Badge created!")
      else
        render :new
      end
    end
    #
    def show

    end

    def edit
      # redirect_to root_path, alert: "Access denied." unless can? :edit, @badge
    end

    def update
      if @badge.update(badge_params)
        redirect_to badges_path, notice: "Badge updated!"
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy
      flash[:notice] = "Badge deleted successfully"
      redirect_to badges_path
    end


end

CodeDrillz/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @drills = Drill.all
    @user_drill = UserDrill.all
  end

  def create
    drill_params = params.permit(:drill_id)
    @user_drill = UserDrill.new(drill_params)
    @user_drill.user = current_user

    if @user_drill.save
      redirect_to(homes_path, notice: "user drill created!")
    else
      render :new
    end
    # render text: drill_params
  end

  def destroy
    @user_drill ||= UserDrill.find params[:id]
    @user_drill.destroy
    flash[:notice] = "Drill deleted successfully"
    redirect_to homes_path
  end

end

CodeDrillz/app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  unless user_signed_in?
    redirect_to root_path
  end
end

end

CodeDrillz/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

CodeDrillz/app/helpers/badges_helper.rb
module BadgesHelper
end

CodeDrillz/app/helpers/categories_helper.rb
module CategoriesHelper
end

CodeDrillz/app/helpers/drills_helper.rb
module DrillsHelper
end

CodeDrillz/app/helpers/groups_helper.rb
module GroupsHelper
end

CodeDrillz/app/helpers/homes_helper.rb
module HomesHelper
end

CodeDrillz/app/helpers/users_helper.rb
module UsersHelper
end

CodeDrillz/app/views/homes/_all_drill.html.erb
  <div class="all-drills text-center">
    <% @drills.each do |drill| %>
      <div class="drill-box flippin">
        <div class="front card">
            <p class="drill-content">
              <%= drill.description.upcase %><br>
            </p>
        </div>
        <div class="back card">
          <p class="drill-back">
            <%= link_to "Add to my Drills", add_drill_path(drill),
                        class: "btn2 btn-success-card", method: :post %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

CodeDrillz/app/views/homes/_my_drill.html.erb
<div>
  <% if @user_drill %>
    <% @user_drill.each do |d| %>

      <div class="drill-box">
        <div class="my-drill">
          <div class="text-center"><%= d.drill.description.upcase %></div>
          <br>
          <div>
            Taken: 3 times<br>
            Score: 70%
          </div>
          <br>
          <div>
            <%= link_to "Start", group_drill_path(d.drill.group.id, d.drill_id), class: "btn-drill" %>
            <%= link_to "Remove", home_path(d), class: "btn-drill",
                    method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

CodeDrillz/app/views/homes/index.html.erb
<div class="tabs-border">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">All Drills</a></li>
    <% if user_signed_in? %>
    <li><a data-toggle="tab" href="#mydrill">My Drills</a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <%= render "all_drill" %>
    </div>
    <% if user_signed_in? %>
    <div id="mydrill" class="tab-pane fade">
      <%= render "my_drill" %>
    </div>
    <% end %>
  </div>

</div>

CodeDrillz/app/views/homes/welcome.html.erb
<div class="welcome-bg"/>
<div class="caption text-center">
    <h1 class="heading">Welcome to Codecore Drillz</h1>
    <h2>Try our free courses now</h2>
    <!-- <h3>Learn by Doing <br> Try now our free course</h3> -->

    <%#= link_to "Enter", homes_path, class: "btn btn-default btn-cta fa fa-chevron-right" %>
    <div>
      <br><br>
    </div>
    <%= link_to "CREATE FREE ACCOUNT", new_user_registration_path, class: "btn2 btn-success-2" %>
</div>