CodeDrillz/config/routes.rb
Rails.application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # devise_for :users, ActiveAdmin::Devise.config
  # , ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :groups do
    resources :drills
  end

  resources :categories
  get "/users/profile" => "users#show", as: :profile
  resources :users
  # devise_for :users, controllers: {
          # sessions: 'users/sessions'
        # }

  # get "users/create" => "users#create", as: :user_sign_up

  post "/homes/:drill_id/add" => "homes#create", as: :add_drill

  resources :homes
  resources :badges
  root "homes#welcome"
  get "/welcome" => "homes#welcome", as: :welcome


end
# every single file in views/users is junk & should eventually be deleted.
# everything you'd think to be in that folder is actually in views/devise

CodeDrillz/app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :earned_badges, through: :groups
end

CodeDrillz/app/controllers/badges_controller.rb
class BadgesController < ApplicationController

    before_action :badge, only: [:show, :edit, :update, :destroy]

    # ----------------------------------------------------------------------------
      def badge
        @badge ||= Badge.find params[:id]
      end
      def badge_params
        params.require(:badge).permit([:url])
      end
    # ----------------------------------------------------------------------------

    def index
      @badge = Badge.all
    end

    def new
      @badge = Badge.new
    end

    def create
      # render text: badge_params

      @badge = Badge.new(badge_params)
      # @badge.user = current_user
      if @badge.save
        redirect_to(badges_path, notice: "Badge created!")
      else
        render :new
      end
    end
    #
    def show

    end

    def edit
      # redirect_to root_path, alert: "Access denied." unless can? :edit, @badge
    end

    def update
      if @badge.update(badge_params)
        redirect_to badges_path, notice: "Badge updated!"
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy
      flash[:notice] = "Badge deleted successfully"
      redirect_to badges_path
    end


end

CodeDrillz/app/helpers/badges_helper.rb
module BadgesHelper
end

CodeDrillz/app/views/badges/index.html.erb
<h1 class="text-center">Badges Index</h1>
<div>
  <!--  class="margin-top-30" -->
  <span><%= link_to "add new badge", new_badge_path, class: "btn2 btn-success" %></span>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>url</th>
        <td>image</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% num = 0 %>
      <% @badge.each do |b| %>
      <% num += 1 %>
      <tr><td><%= num %></td>
          <td><%= b.url %></td>
          <td><img src="<%= b.url %>" width="50px;"></td>
          <td><%= link_to "edit", edit_badge_path(b), class: "glyphicon glyphicon-edit" %>
              <%= link_to "delete", badge_path(b), class: "glyphicon glyphicon-trash",
                          method: :delete,
                          data: {confirm: "Are you sure?"} %>
          </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>