CodeDrillz/config/routes.rb
Rails.application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # devise_for :users, ActiveAdmin::Devise.config
  # , ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :groups do
    resources :drills
  end

  resources :categories
  get "/users/profile" => "users#show", as: :profile
  resources :users
  # devise_for :users, controllers: {
          # sessions: 'users/sessions'
        # }

  # get "users/create" => "users#create", as: :user_sign_up

  post "/homes/:drill_id/add" => "homes#create", as: :add_drill

  resources :homes
  resources :badges
  root "homes#welcome"
  get "/welcome" => "homes#welcome", as: :welcome


end
# every single file in views/users is junk & should eventually be deleted.
# everything you'd think to be in that folder is actually in views/devise

CodeDrillz/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

CodeDrillz/app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :earned_badges, through: :groups
end

CodeDrillz/app/models/categorizing.rb
class Categorizing < ActiveRecord::Base
  belongs_to :category
  belongs_to :group
end

CodeDrillz/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorizings, dependent: :nullify
  has_many :groups, through: :categorizings

  validates :title, presence: true

  
end

CodeDrillz/app/models/drill.rb
class Drill < ActiveRecord::Base
  belongs_to :group
  has_many   :solutions, dependent: :destroy
  accepts_nested_attributes_for :solutions, reject_if: :all_blank, allow_destroy: true
  has_many :user_drills, dependent: :destroy
  has_many :user, through: :user_drills

  validates :description, presence: true

  def to_s
    self.description
  end

end

CodeDrillz/app/models/earned_badge.rb
class EarnedBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  belongs_to :group
end

CodeDrillz/app/models/group.rb
class Group < ActiveRecord::Base

  has_many :categories, through: :categorizings
  # belongs_to :user

  has_many :drills, dependent: :destroy
  has_many :categorizings, dependent: :nullify
  has_many :categories, through: :categorizings
  has_many :group_badges, dependent: :nullify
  has_many :badges, through: :group_badges
  has_many :earned_badges, dependent: :nullify

  validates :name, presence: true
  validates :level, presence: true
end

CodeDrillz/app/models/group_badge.rb
class GroupBadge < ActiveRecord::Base
  belongs_to :group
  belongs_to :badge
end

CodeDrillz/app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
end

CodeDrillz/app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :drill

  validates :correct_answer, presence: true
  validates :solution_type, presence: true
end

CodeDrillz/app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_many :points, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :earned_badges, through: :groups
  has_many :user_drills, dependent: :destroy
  has_many :drills, through: :user_drills

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def self.send_reset_password_instructions(attributes={})
     recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
     if !recoverable.approved?
       recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
     elsif recoverable.persisted?
       recoverable.send_reset_password_instructions
     end
     recoverable
   end
end

CodeDrillz/app/models/user_drill.rb
class UserDrill < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill
end

CodeDrillz/app/controllers/badges_controller.rb
class BadgesController < ApplicationController

    before_action :badge, only: [:show, :edit, :update, :destroy]

    # ----------------------------------------------------------------------------
      def badge
        @badge ||= Badge.find params[:id]
      end
      def badge_params
        params.require(:badge).permit([:url])
      end
    # ----------------------------------------------------------------------------

    def index
      @badge = Badge.all
    end

    def new
      @badge = Badge.new
    end

    def create
      # render text: badge_params

      @badge = Badge.new(badge_params)
      # @badge.user = current_user
      if @badge.save
        redirect_to(badges_path, notice: "Badge created!")
      else
        render :new
      end
    end
    #
    def show

    end

    def edit
      # redirect_to root_path, alert: "Access denied." unless can? :edit, @badge
    end

    def update
      if @badge.update(badge_params)
        redirect_to badges_path, notice: "Badge updated!"
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy
      flash[:notice] = "Badge deleted successfully"
      redirect_to badges_path
    end


end

CodeDrillz/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_action :find_group, {only: [:show, :edit, :update, :destroy]}
 #  before_action :authenticate_user, except: [:index, :show]
 #  before_action :authorize, only: [:edit, :update, :destroy]

 	def index
 		@groups = Group.all
 	end

  def new
    # authenticate_user
    @categories = Category.all
    @group = Group.new

		@badges = Merit::Badge.all
  end

  def create
		# render text: params
    @group = Group.new(group_params)
    # @group.user = current_user
    if @group.save
      redirect_to(group_path(@group))
    else
      render :new
    end
  end

  def show
  end

  def edit
    # redirect_to groups_path, alert: "Access Denied"
  end

  def update
    if  @group.update(group_params)
      redirect_to group_path(@group), notice: "group updated!"
    else
      render :edit
    end
  end

  def index
    @groups = Group.all
  end

  def destroy
    @group.destroy
    flash[:notice] = "group deleted!"
    redirect_to groups_path
  end

  # def authorize
  #   redirect_to groups_path, alert: "Access Denied" unless can? :manage, @q
  # end

  private

  def find_group
    @group = Group.find params[:id]
  end

  def group_params
    params.require(:group).permit(:name, :description, :level, :badge, :points, {category_ids:[]})
  end

end

CodeDrillz/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @drills = Drill.all
    @user_drill = UserDrill.all
  end

  def create
    drill_params = params.permit(:drill_id)
    @user_drill = UserDrill.new(drill_params)
    @user_drill.user = current_user

    if @user_drill.save
      redirect_to(homes_path, notice: "user drill created!")
    else
      render :new
    end
    # render text: drill_params
  end

  def destroy
    @user_drill ||= UserDrill.find params[:id]
    @user_drill.destroy
    flash[:notice] = "Drill deleted successfully"
    redirect_to homes_path
  end

end

CodeDrillz/app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  unless user_signed_in?
    redirect_to root_path
  end
end

end

CodeDrillz/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

CodeDrillz/app/helpers/badges_helper.rb
module BadgesHelper
end

CodeDrillz/app/helpers/categories_helper.rb
module CategoriesHelper
end

CodeDrillz/app/helpers/drills_helper.rb
module DrillsHelper
end

CodeDrillz/app/helpers/groups_helper.rb
module GroupsHelper
end

CodeDrillz/app/helpers/homes_helper.rb
module HomesHelper
end

CodeDrillz/app/helpers/users_helper.rb
module UsersHelper
end

CodeDrillz/app/views/groups/_form.html.erb
<%= @group.errors.full_messages.join(", ") %>

<div class="form-horizontal">

  <!-- <fieldset> -->

  <!--  form  -->
    <%= form_for @group do |f|  %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description%>
        <%= f.text_area :description, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.radio_button("level", "1") %>
        <%= f.label :level, "Beginner", :value => "1" %>

        <%= f.radio_button("level", "2") %>
        <%= f.label :level, "Intermediate", :value => "2" %>

        <%= f.radio_button("level", "3") %>
        <%= f.label :level, "Advanced", :value => "3" %>

      </div>

      <!-- Using dummy for now since we are not sure about badges -->
      <div class="form-group">

        <%= f.collection_radio_buttons(:badge, Merit::Badge.all, :id, :custom_fields) do |b|
            b.label {
               b.radio_button + image_tag(b.object.custom_fields[:url], width: 50)
            }
        end %>

      </div>
      <div class="form-group">
        <%= f.label :points%>
        <%= f.text_field :points, class: "form-control"%>
      </div>
      <div class="form-group">
      <%= f.label :categories%>
      <%#= f.collection_check_boxes :category_ids, Category.order(:title), :id, :title    %>
      <%= f.collection_select(:category_ids, Category.all, :id, :title, {}, multiple: "multiple", class: "form-control chosen-select", id:"chosen-select", "data-placeholder" => "Add Categories") %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn2 btn-success" %>
      </div>
    <% end %>

  <!-- </fieldset> -->
</div>

CodeDrillz/app/views/groups/edit.html.erb
<h3 class="text-center">Edit</h3>

<%= render "form" %>

CodeDrillz/app/views/groups/index.html.erb
<h2 class="text-center">Drillz Group</h2>
<br>

<table class="table table-striped">
  <tbody>


  <% @groups.each do |group| %>
    <tr>
      <td> <%= link_to group.name, group_path(group)%> </td>
      <td style="text-align: right">
        <%= link_to fa_icon("pencil-square-o"), edit_group_path(group), class: "icon-big" %>
        <%= link_to fa_icon("trash-o"), group_path(group), method: :delete,
                  class: "icon-big", data: {confirm: "Are you sure ?"}%>
      </td>
    </tr>
  <% end%>

  </tbody>
</table>

<div class="text-right">
  <%= link_to "Create a new group", new_group_path, class: "btn2 btn-success" %>
</div>

CodeDrillz/app/views/groups/new.html.erb
<h3 class="text-center">Create a new Group</h3>

<%= render "form" %>

CodeDrillz/app/views/groups/show.html.erb
<h2>Drill Group - <%= @group.name%></h2>

<p><%= @group.description%></p>

<% @group.categories.each do |cat| %>
  <%= cat.title%>
<% end %>
<br>
<% badge = Merit::Badge.find(@group.badge.to_i) %>
<%= image_tag(badge.custom_fields[:url], width: 50) %>
<p class="text-right">

  <%= link_to fa_icon("pencil-square-o"), edit_group_path(@group), class: "icon-big" %>
  <%= link_to fa_icon("trash-o"), group_path(@group), method: :delete, class: "icon-big",
                                                  data: {confirm: "Are you sure ?"} %>
</p>

<table class="table table-striped">
  <tbody>
    <% @group.drills.each do |drill| %>
    <tr>
      <td>
        <%= drill.description %>
      </td>
      <td style="text-align: right">
        <%= link_to fa_icon("pencil-square-o"), edit_group_drill_path(@group, drill), class: "icon-big"  %>
        <%= link_to fa_icon("trash-o"), group_drill_path(@group, drill),
                    method: :delete, data: {confirm: "Are you sure?"}, class: "icon-big"  %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<div class="text-right">
  <%= link_to "Create a new Drill", new_group_drill_path(@group), class:"btn2 btn-success" %>
</div>