CodeDrillz/config/routes.rb
Rails.application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # devise_for :users, ActiveAdmin::Devise.config
  # , ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  resources :groups do
    resources :drills
  end

  resources :categories
  get "/users/profile" => "users#show", as: :profile
  resources :users
  # devise_for :users, controllers: {
          # sessions: 'users/sessions'
        # }

  # get "users/create" => "users#create", as: :user_sign_up

  post "/homes/:drill_id/add" => "homes#create", as: :add_drill

  resources :homes
  resources :badges
  root "homes#welcome"
  get "/welcome" => "homes#welcome", as: :welcome


end
# every single file in views/users is junk & should eventually be deleted.
# everything you'd think to be in that folder is actually in views/devise

CodeDrillz/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

CodeDrillz/app/models/badge.rb
class Badge < ActiveRecord::Base
  has_many :earned_badges, through: :groups
end

CodeDrillz/app/models/categorizing.rb
class Categorizing < ActiveRecord::Base
  belongs_to :category
  belongs_to :group
end

CodeDrillz/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categorizings, dependent: :nullify
  has_many :groups, through: :categorizings

  validates :title, presence: true

  
end

CodeDrillz/app/models/drill.rb
class Drill < ActiveRecord::Base
  belongs_to :group
  has_many   :solutions, dependent: :destroy
  accepts_nested_attributes_for :solutions, reject_if: :all_blank, allow_destroy: true
  has_many :user_drills, dependent: :destroy
  has_many :user, through: :user_drills

  validates :description, presence: true

  def to_s
    self.description
  end

end

CodeDrillz/app/models/earned_badge.rb
class EarnedBadge < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  belongs_to :group
end

CodeDrillz/app/models/group.rb
class Group < ActiveRecord::Base

  has_many :categories, through: :categorizings
  # belongs_to :user

  has_many :drills, dependent: :destroy
  has_many :categorizings, dependent: :nullify
  has_many :categories, through: :categorizings
  has_many :group_badges, dependent: :nullify
  has_many :badges, through: :group_badges
  has_many :earned_badges, dependent: :nullify

  validates :name, presence: true
  validates :level, presence: true
end

CodeDrillz/app/models/group_badge.rb
class GroupBadge < ActiveRecord::Base
  belongs_to :group
  belongs_to :badge
end

CodeDrillz/app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user
end

CodeDrillz/app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :drill

  validates :correct_answer, presence: true
  validates :solution_type, presence: true
end

CodeDrillz/app/models/user.rb
class User < ActiveRecord::Base
  has_merit

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_many :points, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :earned_badges, through: :groups
  has_many :user_drills, dependent: :destroy
  has_many :drills, through: :user_drills

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def self.send_reset_password_instructions(attributes={})
     recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
     if !recoverable.approved?
       recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
     elsif recoverable.persisted?
       recoverable.send_reset_password_instructions
     end
     recoverable
   end
end

CodeDrillz/app/models/user_drill.rb
class UserDrill < ActiveRecord::Base
  belongs_to :user
  belongs_to :drill
end

CodeDrillz/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @drills = Drill.all
    @user_drill = UserDrill.all
  end

  def create
    drill_params = params.permit(:drill_id)
    @user_drill = UserDrill.new(drill_params)
    @user_drill.user = current_user

    if @user_drill.save
      redirect_to(homes_path, notice: "user drill created!")
    else
      render :new
    end
    # render text: drill_params
  end

  def destroy
    @user_drill ||= UserDrill.find params[:id]
    @user_drill.destroy
    flash[:notice] = "Drill deleted successfully"
    redirect_to homes_path
  end

end

CodeDrillz/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

CodeDrillz/app/helpers/badges_helper.rb
module BadgesHelper
end

CodeDrillz/app/helpers/categories_helper.rb
module CategoriesHelper
end

CodeDrillz/app/helpers/drills_helper.rb
module DrillsHelper
end

CodeDrillz/app/helpers/groups_helper.rb
module GroupsHelper
end

CodeDrillz/app/helpers/homes_helper.rb
module HomesHelper
end

CodeDrillz/app/helpers/users_helper.rb
module UsersHelper
end

CodeDrillz/app/views/layouts/_flash_messages.html.erb
<br>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>

CodeDrillz/app/views/layouts/_nav.html.erb
<nav class="nav navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <nav class="navbar-brand">
        <a href="/"><%= image_tag "codecore_drillz_logo.png" %></a>
      </nav>
    </div>



    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><%= link_to "Home", root_path %></li> -->
        <li><%= link_to "Drillz", homes_path %></li>
        <li><%= link_to "Badge" %></li>
        <li><%= link_to "Categories", categories_path %></li>

      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="navbar-form  nav navbar-right">
        <% if admin_user_signed_in? %>
        <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Manage Drill Groups", groups_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Manage Categories", categories_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Admin Logout", destroy_admin_user_session_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>
        <% if !user_signed_in? && !admin_user_signed_in?%>
          <%= link_to "LOG IN", new_user_session_path, class: "btn2 btn-success-2" %>
          <%= link_to "CREATE FREE ACCOUNT", new_user_registration_path, class: "btn2 btn-success" %>
        <% else %>
        <ul class="nav navbar-nav">
        <li class="dropdown">
            <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= current_user.first_name.capitalize %> <span class="caret"></span></a>
          <% end %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
         <% end %>
        <!-- <li><a href="#">Link</a></li> -->
      </ul>
    </div>
  </div>
</nav>

CodeDrillz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CodeDrillz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://cdn.rawgit.com/nnattawat/flip/v1.0.18/dist/jquery.flip.min.js"></script>

</head>

<body>

  <%= render "/layouts/nav" %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">

          <%= render "/layouts/flash_messages" %>
          <%= yield %>

        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
</body>

</html>